# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
#PROVISIONINGENGINE_CAMEL_URL: "http://192.168.113.104:80/CloudWebPortal"
PROVISIONINGENGINE_CAMEL_URL: "http://192.168.113.104:80/ProvisioningEngine"
WEBPORTAL_PROVISIONINGBUTTON_VISIBLE: "false"
WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE: "false"
WEBPORTAL_PROVISIONINGOBJECTS_EDIT_VISIBLE: "false"
WEBPORTAL_PROVISIONINGTASKS_EDIT_VISIBLE: "false"
WEBPORTAL_PROVISIONINGTASKS_DESTROY_VISIBLE: "false"
WEBPORTAL_BASEURL: "/"
WEBPORTAL_SIMULATION_MODE: "true"