# Add application configuration variables here, as shown below.
#
PROVISIONINGENGINE_CAMEL_URL: "http://192.168.113.104:80/ProvisioningEngine"
WEBPORTAL_PROVISIONINGBUTTON_VISIBLE: "false"
WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE: "false"
WEBPORTAL_PROVISIONINGOBJECTS_HIDE_INACTIVEBUTTONS: "true"
WEBPORTAL_PROVISIONINGOBJECTS_EDIT_VISIBLE: "false"
WEBPORTAL_PROVISIONINGTASKS_EDIT_VISIBLE: "false"
WEBPORTAL_PROVISIONINGTASKS_DESTROY_VISIBLE: "false"
WEBPORTAL_BASEURL: "/"
#WEBPORTAL_SIMULATION_MODE: "true"
